### ISSUE TITLE
Apakah project ini akan dilanjutkan?

### ISSUE THREAD

**Issue by irfanandratama** [drr3d/JAABF#2]
Permisi mas, selain saya ingin bertanya pertanyaan di atas apa saya boleh minta kontak mas? Saya pengen diskusi soal NER dan chatbot. Terima kasih.

**Comment by drr3d** [comment]
Halo mas Irfan,

boleh mas, kontak nanti saya kirim via email ya mas, bisa ke aulianormansyah@gmail.com

rencana memang pasti saya lanjutkan mas, lagi buntu aja sekarang di chatbot dan juga lagi padet beberapa kegiatan lain mas, sembari cari ide :)

regards,

**Comment by irfanandratama** [comment]
terima kasih mas
